name: Automated Release
on:
  push:
    branches:
      - master  # Trigger on pushes to the `master` branch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Release Tag
        uses: anothrNick/github-tag-action@v1.71.0  # Valid version
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tag-prefix: v